const express = require('express')
const connectDb = require('./src/connections/db')
const app =  express()
const dotEnv = require('dotenv')
const routes = require('./src/routes/transactions')
const cors = require('cors')

dotEnv.config()
connectDb()
app.use(express.json())
app.use(express.urlencoded({extended:true}))
app.use(cors({origin:"*"}))
app.use(routes)
app.listen(process.env.PORT,()=> console.log("server is running at :",process.env.PORT))
